[supervisord]
nodaemon=true
logfile=/dev/null
user=root

[program:apache2]
command=/usr/sbin/apache2ctl -D FOREGROUND
autostart=true
autorestart=true

[program:mariadb]
command=/usr/sbin/mariadbd --user=mysql
autostart=true
autorestart=true

